In [2]:
import numpy as np

# Question 1

In [3]:
# Creating the array using arange

arr = np.arange(2,50,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Question 2

In [5]:
# Creating 2 empty lists

lst1 = [] 
lst2 = []


# Getting 5 inputs for the list 1

for i in range(5):
    x = int(input("Enter the elements for lst1: "))
    lst1.append(x)

    
# Getting 5 inputs for the list 2

for i in range(5):
    x = int(input("Enter the elements for lst2: "))
    lst2.append(x)


# Converting lists into a arrays

arr1 = np.array(lst1)
arr2 = np.array(lst2)


# Concatenating two Arrays (Joining two arrays)

arr = np.concatenate((arr1, arr2))
print("\nvalue of concatenated arr: ",arr)


# Sorting the array

arr = np.sort(arr)
print("\nSorted array of arr: ",arr)

Enter the elements for lst1: 5
Enter the elements for lst1: 7
Enter the elements for lst1: 9
Enter the elements for lst1: 2
Enter the elements for lst1: 3
Enter the elements for lst2: 6
Enter the elements for lst2: 0
Enter the elements for lst2: 1
Enter the elements for lst2: 8
Enter the elements for lst2: 4

value of concatenated arr:  [5 7 9 2 3 6 0 1 8 4]

Sorted array of arr:  [0 1 2 3 4 5 6 7 8 9]


# Question 3

In [3]:
arr = np.array([[1,2,3], [4,5,6]])


# Finding the dimensions of the Array

print("Number of dimensions in array: ", arr.ndim)

# Finding the size of the Array

print("Size of Array: ", arr.ndim)

Number of dimensions in array:  2
Size of Array:  2


# Questions 4

# np.newaxis:

In [56]:
# Creating an array

arr = np.array([1,2,3,4,5,6])
print("Shape of Array: ", arr.shape)
print("Shape of Array:",arr)


# Converting using np.newaxis for rows

arr_row = arr[np.newaxis, :]
print("\nShape of 2d array for row", arr_row.shape)
print("2d Array for rows: ", arr_row)


# Converting using np.newaxis for coloumns

arr_col = arr[:, np.newaxis]
print("\nShape of 2d array for coloumn", arr_col.shape)
print("2d Array for coloumns: \n arr_col)



Shape of Array:  (6,)
Shape of Array: [1 2 3 4 5 6]

Shape of 2d array for row (1, 6)
2d Array for rows:  [[1 2 3 4 5 6]]

Shape of 2d array for coloumn (6, 1)
2d Array for coloumns:  [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


# np.expand_dims:

In [57]:
# Creating an array

arr = np.array([1,2,3,4,5,6])
print("Shape of Array: ", arr.shape)
print("Array", arr)


# Converting using np.expand_dims for rows

arr_row = np.expand_dims(arr,axis=0)
print("\nShape of 2d array for row", arr_row.shape)
print("2d Array for rows: ", arr_row)


# Converting using np.expand_dims for coloumns

arr_col = np.expand_dims(arr,axis=1)
print("\nShape of 2d array for coloumn : ", arr_col.shape)
print("2d Array for coloumns:  \n", arr_col)


Shape of Array:  (6,)
Array [1 2 3 4 5 6]

Shape of 2d array for row (1, 6)
2d Array for rows:  [[1 2 3 4 5 6]]

Shape of 2d array for coloumn :  (6, 1)
2d Array for coloumns:  
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


# Questions 5

In [87]:
arr_1 = np.array([1,2,3,4,5])
arr_2 = np.array([6,7,8,9,10])


# Vertical stack

print("Vertical stack: \n",np.vstack((arr_1, arr_2)))

# Horizontal Stack

print("\nHorizontal Stack: ",np.hstack((arr_1, arr_2)))

Vertical stack: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Horizontal Stack:  [ 1  2  3  4  5  6  7  8  9 10]


# Question 6

In [86]:
# Creating an array

arr = np.array([3,5,15,1,2,5,3,7,9,8,9,6,5,4,2,])


# Getting the unique numbers and counts(getting the frequency of the unique numbers) 

Unique_n_counts = np.unique(arr, return_counts= True)
arr = np.asarray((Unique_n_counts)).T

print(arr)

[[ 1  1]
 [ 2  2]
 [ 3  2]
 [ 4  1]
 [ 5  3]
 [ 6  1]
 [ 7  1]
 [ 8  1]
 [ 9  2]
 [15  1]]
